# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formview.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowCheck(object):
    def setupUi(self, WindowCheck):
        WindowCheck.setObjectName("WindowCheck")
        WindowCheck.resize(819, 845)
        WindowCheck.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(WindowCheck)
        self.centralwidget.setObjectName("centralwidget")
        self.checkin = QtWidgets.QPushButton(self.centralwidget)
        self.checkin.setGeometry(QtCore.QRect(40, 740, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkin.setFont(font)
        self.checkin.setStyleSheet("QPushButton#checkin {\n"
"    border: none;\n"
"    background-color: rgb(85, 255, 0);\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#checkin:pressed {\n"
"    \n"
"    background-color: rgb(170, 255, 127);\n"
"}\n"
"\n"
"QPushButton#checkin:hover {\n"
"    color: rgb(134, 134, 134);\n"
"}")
        self.checkin.setObjectName("checkin")
        self.checkout = QtWidgets.QPushButton(self.centralwidget)
        self.checkout.setGeometry(QtCore.QRect(650, 740, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkout.setFont(font)
        self.checkout.setStyleSheet("QPushButton#checkout {\n"
"    border: none;\n"
"    color: white;\n"
"    background-color: rgb(255, 0, 127);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton#checkout:pressed {\n"
"    background-color: rgb(255, 85, 127);\n"
"}\n"
"\n"
"QPushButton#checkout:hover {\n"
"    color: rgb(134, 134, 134);\n"
"}")
        self.checkout.setObjectName("checkout")
        self.view = QtWidgets.QLabel(self.centralwidget)
        self.view.setGeometry(QtCore.QRect(60, 10, 701, 551))
        self.view.setStyleSheet("border: 2px solid rgb(85, 170, 255);\n"
"")
        self.view.setText("")
        self.view.setObjectName("view")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 620, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textStatus = QtWidgets.QTextBrowser(self.centralwidget)
        self.textStatus.setGeometry(QtCore.QRect(130, 610, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.textStatus.setFont(font)
        self.textStatus.setObjectName("textStatus")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(560, 580, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(560, 640, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lcdNumber_2.setFont(font)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        WindowCheck.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WindowCheck)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 819, 26))
        self.menubar.setObjectName("menubar")
        WindowCheck.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WindowCheck)
        self.statusbar.setObjectName("statusbar")
        WindowCheck.setStatusBar(self.statusbar)

        self.retranslateUi(WindowCheck)
        QtCore.QMetaObject.connectSlotsByName(WindowCheck)

    def retranslateUi(self, WindowCheck):
        _translate = QtCore.QCoreApplication.translate
        WindowCheck.setWindowTitle(_translate("WindowCheck", "MainWindow"))
        self.checkin.setText(_translate("WindowCheck", "Check In"))
        self.checkout.setText(_translate("WindowCheck", "Check Out"))
        self.label.setText(_translate("WindowCheck", "Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowCheck = QtWidgets.QMainWindow()
    ui = Ui_WindowCheck()
    ui.setupUi(WindowCheck)
    WindowCheck.show()
    sys.exit(app.exec_())
