# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "border-radius: 5px;\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 10, 811, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: blue;\n"
                                   "color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 140, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border: none;\n"
                                      "\n"
                                      "border-bottom: 3px solid rgb(176, 176, 176);\n"
                                      "background-color: qradialgradient(stop:1 rgba(255, 255, 255, 0));")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 260, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border: none;\n"
                                      "\n"
                                      "border-bottom: 3px solid rgb(176, 176, 176);\n"
                                      "background-color: qradialgradient(stop:1 rgba(255, 255, 255, 0));")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 360, 471, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
                                      "QPushButton#pushButton {\n"
                                      "    background-color: rgb(0, 255, 0);\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    border-radius: 20px;\n"
                                      "\n"
                                      "}\n"
                                      "QPushButton#pushButton:pressed{\n"
                                      "    background-color: rgb(85, 255, 127);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton#pushButton:hover{\n"
                                      "    \n"
                                      "    \n"
                                      "    color: rgb(120, 120, 120);\n"
                                      "}\n"
                                      "")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 460, 471, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("\n"
                                        "\n"
                                        "QPushButton#pushButton_2 {\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(255, 0, 127);\n"
                                        "    border-radius: 20px;\n"
                                        "    \n"
                                        "\n"
                                        "}\n"
                                        "QPushButton#pushButton_2:pressed{\n"
                                        "    \n"
                                        "    background-color: rgb(255, 0, 0);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton#pushButton_2:hover{\n"
                                        "    \n"
                                        "    \n"
                                        "    color: rgb(120, 120, 120);\n"
                                        "}\n"
                                        "")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "HỆ THỐNG CHẤM CÔNG BẰNG KHUÔN MẶT"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Nhập tên tài khoản"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Nhập mật khẩu"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancle"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    MainWindow.show()
    sys.exit(app.exec_())

